#!/bin/bash
sudo apt update -y
sudo apt install openjdk-8-jre-headless -y
ufw allow 25565
WORK_DIR='/home/vagrant/minecraft' 
mkdir ${WORK_DIR}
cd ${WORK_DIR}
wget https://launcher.mojang.com/v1/objects/c5f6fb23c3876461d46ec380421e42b289789530/server.jar
touch ${WORK_DIR}/eula.txt
cat > ${WORK_DIR}/eula.txt <<EULA
# By changing the setting below to TRUE you are indicating your agreement to our EULA (https://account.mojang.com/documents/minecraft_eula).
eula=TRUE
EULA
touch ${WORK_DIR}/start.sh
cat > ${WORK_DIR}/start.sh <<START
screen -dmS minecraft java -Xms1024M -Xmx1024M -jar server.jar nogui
START
chmod +x ${WORK_DIR}/start.sh
sh ${WORK_DIR}/start.sh
