php:
  build: .
  links:
    - php_db:mysql
    - maildev:maildev
  ports:
    - 4321:80

php_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: examplepass

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - php_db:db
  ports:
    - 8765:80
  environment:
    PMA_USER: root
    PMA_PASSWORD: examplepass
    PHP_UPLOAD_MAX_FILESIZE: 100MB

maildev:
  image: djfarrelly/maildev
  ports:
   - 9876:80
